### PR TITLE
Extend `ImmutableMapRules` Refaster rule collection

### LINKED ISSUE #1223: Rewrite `ImmutableMap.Builder#build` to `#buildOrThrow`
### Problem

An `ImmutableMap.Builder` has two terminal methods which accomplish the same thing: `build` or `buildOrThrow`.

The `buildOrThrow` method should be preferred, because the documentation of `build` specifies:

> Prefer the equivalent method {@link #buildOrThrow()} to make it explicit that the method will throw an exception if there are duplicate keys. The {@code build()} method will soon be deprecated.

### Description of the proposed new feature

- [ ] Support a stylistic preference.
- [x] Avoid a common gotcha, or potential problem.
    - Make the behavior evident: an exception may be thrown (in case of duplicate keys).
- [ ] Improve performance.

I would like to rewrite the following code:
```java
ImmutableMap.Builder<K, V> builder = ImmutableMap.builder();
builder.build();
```

to:
```java
ImmutableMap.Builder<K, V> builder = ImmutableMap.builder();
builder.buildOrThrow();
```

### PR DESCRIPTION
**Pull request by Stephan202**
I set out to resolve #1223, then noticed a few other ways in which internal code can be simplified.

Suggested commit message:
```
Extend `ImmutableMapRules` Refaster rule collection (#1488)

Resolves #1223.
```

### CODE REVIEW

File: error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ImmutableMapRules.java [hunk 1]
```diff
@@ -44,12 +45,28 @@ ImmutableMap.Builder<K, V> after() {
...
+    @BeforeTemplate
+    ImmutableMap<K, V> before(ImmutableMap.Builder<K, V> builder) {
+      return builder.build();
+    }
+
+    @AfterTemplate
+    ImmutableMap<K, V> after(ImmutableMap.Builder<K, V> builder) {
+      return builder.buildOrThrow();
+    }
+  }
```
Comment (Stephan202) [inline error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ImmutableMapRules.java:62]: The builder subtypes for `ImmutableBiMap` and `ImmutableSortedMap` extend from `ImmutableMap.Builder`, so those `build()` calls are also covered.

File: error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ImmutableMapRules.java [hunk 2]
```diff
@@ -139,8 +157,6 @@ abstract static class StreamOfMapEntriesToImmutableMap<E, K, V> {
     @Placeholder(allowsIdentity = true)
     abstract V valueFunction(@MayOptionallyUse E element);
 
-    // XXX: We could add variants in which the entry is created some other way, but we have another
-    // rule that covers canonicalization to `Map.entry`.
```
Comment (Stephan202) [inline error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ImmutableMapRules.java:143]: Dropped, because this describes our approach more generally these days.

**Review by Stephan202 — COMMENTED** [review]
Some context.

**Review by mohamedsamehsalah — APPROVED** [review]
LGTM 🚀 

Nice suggestion @EnricSala 🙌

File: integration-tests/prometheus-java-client-expected-changes.patch [hunk 3]
```diff
@@ -4565,15 +4603,24 @@
...
 -class PrometheusMetricDataTest {
 +final class PrometheusMetricDataTest {
  
    Map<Object, Object> translations =
-       Map.ofEntries(
+-      Map.ofEntries(
++      ImmutableMap.ofEntries(
+           entry("days", "d"),
+           entry("hours", "h"),
+           entry("minutes", "min"),
```
Comment (Stephan202) [inline integration-tests/prometheus-java-client-expected-changes.patch:4623]: This isn't simplified further, because it's a _long_ list. We could add more rules, but: meh.

**Review by Stephan202 — COMMENTED** [review]
Rebased and updated the integration test expectations.

**Review by rickie — APPROVED** [review]
✨
